Detect missing attribute early.
Would otherwise fail with the unhelpful message:
UnboundLocalError: cannot access local variable 'members' where it is not associated with a value